platform:'ios','8.0'
use_frameworks!

def layout
    pod 'Masonry'
end

def reactnative
    pod 'React',:path => '../node_modules/react-native',:subspecs => [
        'Core',
        'ART',
        'RCTActionSheet',
        'RCTAdSupport',
        'RCTGeolocation',
        'RCTImage',
        'RCTNetwork',
        'RCTPushNotification',
        'RCTSettings',
        'RCTText',
        'RCTVibration',
        'RCTWebSocket',
        'RCTLinkingIOS'
    ]
    pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
end

target 'RNHotUpdate' do
    layout
    reactnative
end
